[package]
name = "systemctl-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
indexmap = "1.8"
toml = "0.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.tokio]
version = "1.0"
features = ["process", "rt-multi-thread"]
