[package]
name = "systemctl-bot"
version = "0.4.1"
description = "Control your Linux server from Discord"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
indexmap = "1.8"
tokio-stream = "0.1"

[dependencies.clap]
version = "4.0"
features = ["derive"]

[dependencies.config]
version = "0.13"
default-features = false
features = ["toml"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["cache", "client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.tokio]
version = "1.18"
features = ["process", "rt-multi-thread"]

[dependencies.zbus]
version = "3.2"
default-features = false
features = ["tokio"]
