[package]
name = "systemctl-bot"
version = "0.1.0"
description = "Control your Linux server from Discord"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
indexmap = "1.8"
toml = "0.5"

[dependencies.clap]
version = "3.1"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["cache", "client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.tokio]
version = "1.0"
features = ["process", "rt-multi-thread"]
